app/models.py
from . import db
from flask_login import UserMixin
from . import login_manager
from werkzeug.security import generate_password_hash,check_password_hash

class Users(UserMixin,db.Model):
    __tablename__='users'
    id=db.Column(db.Integer,primary_key=True)
    username=db.Column(db.String(150),index=True)
    email=db.Column(db.String(150),unique=True,index=True)
    pass_secure=db.Column(db.String(100))
    blogs=db.relationship('Blogs',backref='user',lazy='dynamic')
    comments=db.relationship('Comments',backref='user',lazy='dynamic')
    code = db.Column(db.Integer,unique=True)

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

class Blogs(db.Model):
    __tablename__='blogs'
    id=db.Column(db.Integer,primary_key=True)
    title=db.Column(db.String(100))
    description=db.Column(db.String(250))
    user_id=db.Column(db.Integer,db.ForeignKey('users.id'))

    @classmethod
    def delete_blog(cls,id):
        blog=Blogs.query.filter_by(id=id).first()
        db.session.delete(blog)
        db.session.commit

class Comments(db.Model):
    __tablename__='comments'
    id=db.Column(db.Integer,primary_key=True)
    comment=db.Column(db.String(250))
    user_id=db.Column(db.Integer,db.ForeignKey('users.id'))

@login_manager.user_loader
def load_user(user_id):
    return Users.query.get(user_id)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,ValidationError
from wtforms.validators import Required
from ..models import Blogs

class Blog(FlaskForm):
    title= StringField('Enter title',validators=[Required()])
    description=TextAreaField('Add your blog',validators=[Required()])
    submit=SubmitField('Submit')

class Comment(FlaskForm):
    comment=TextAreaField('Enter your comment',validators=[Required()])
    submit=SubmitField('Submit')

app/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import config_options
from flask_mail import Mail
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads,IMAGES
from flask_bootstrap  import Bootstrap

login_manager=LoginManager()
login_manager.session_protection ='strong'
login_manager.login_view='auth.login' 
db=SQLAlchemy()
bootstrap=Bootstrap()
mail=Mail()
photos=UploadSet('photos',IMAGES)


def create_app(config_name):
    app = Flask(__name__ )
    app.secret_key = os.urandom(24)


    
    app.config.from_object(config_options[config_name])
    
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    #main blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    #auth blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/authenticate')

    return app

  

app/main/__init__.py
from flask import Blueprint
main =Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,url_for,request,abort,redirect
from flask_login import login_required
from . import main
from .forms import Blog,Comment
from .. import db
from ..models import Users,Blogs,Comments

@main.route('/',methods=['GET','POST'])
def index():
    blog_form=Blog()
    users = Users.query.filter_by(username='uname').first()
    if blog_form.validate_on_submit():
        blogs = Blogs(title=blog_form.title.data,description=blog_form.description.data)
        db.session.add(blogs)
        db.session.commit()
        return redirect(url_for('main.index'))
    
    def delete_blog(id):
        Blogs.delete_blog(id)
    blogs=Blogs.query.all()
    comments=Comments.query.filter_by(comment='comment').first()
    title='Home-The Blogger'
    message='The Blogger'
    return render_template('index.html',message=message,title=title,users=users,blogs=blogs,comments=comments,blog_form=blog_form,delete_blog=delete_blog)
    


@main.route('/user/<uname>', methods=['GET','POST'])
@login_required
def profile(uname):
    users=Users.query.filter_by(username=uname).first()
    blogs=Blogs.query.filter_by(user_id=users.id)
    if users is None:
        abort(404)
    title=f'{Users.username}-The Blogger'
    return render_template('profile/profile.html',title=title,users=users,blogs=blogs)

@main.route('/comments/<uname>', methods=['GET','POST'])
@login_required
def comments(uname):
    form=Comment()
    if form.validate_on_submit():
        comments = Comments(comment=form.comment.data)
        db.session.add(comments)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('comment.html',form=form)

app/templates/base.html
{%extends 'bootstrap/base.html'%}

{% block navbar %}
    {% include 'navbar.html' %}
  {% endblock %}
  {% block content%}
  {% endblock %}

app/templates/blog.html
{%block content%}
<div class="container" style="font-family: 'Indie Flower', cursive;">
    <div class="row">
        <h3>{{blog.blog_title}}</h3>
        <hr>
        <p>{{blog.blog_content}}</p>
        <span>
        <p>Posted on {{date}} by {{blog.user.username| capitalize}}</p>
        <a href="/blog/{{user.id}}?like=1">
            <i class="far fa-thumbs-up"></i>
        </a>{{blog.likes}} <a href="/blog/{{user.id}}?dislike=1">
            <i class="far fa-thumbs-down"></i>
        </a>{{blog.dislikes}}</span>

    </div>
    <div class="row">
        <h4>Comments</h4>
        <hr>
        {% if current_user.is_authenticated %}
            {{ wtf.quick_form(comment_form) }}
        {%endif%}
        {{macro.displayComments(comments)}}
    </div>

</div>
{%endblock%}

app/templates/comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      {{wtf.quick_form(form)}}
    </div>
    <div class="col-md-3"></div>
  </div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block styles %}
  {{ super() }}
  <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
  <link rel="icon" href="{{url_for('static',filename='favicon/img.png')}}">
  <link rel="stylesheet" href="{{url_for('static',filename='css/index.css') }}">
{% endblock %}
{%block content %}
<h1 class='text-center'>{{message}}</h1> <hr>
<br>
<div class="container">
  <div class="row">
    <div class="col1 col-md-8">
      <h2>Latest Blogs</h2>
      <div class="row">
        {% for blog in blogs %}
        <div class="col-sm-6">
          <ul class='list-unstyled '>
            <li class='style'>
              <h3 class=text-primary>{{blog.title}}</h3>
              <h4>{{blog.description}}</h4>
              <!-- <p>By: {{blog.user.username}}</p> -->
              
              <a href="{{url_for('main.comments',uname = current_user.username)}}"><button class='btn btn-primary'>Comment</button></a>
              
            </li> <hr> <br>
            </ul>
        </div>
        {% endfor %}
      
      </div>
    </div>
    <div class="col col-md-4">
      {{wtf.quick_form(blog_form)}}
    </div>
  </div>
</div>


{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role='navigaation'>
  <div class="container-fluid">
    <div class="navbar-header">
      <button type='button' class="navbar-toggle" data-toggle="collapse" data-target='.navbar-collapse'>
      <span class='icon-bar'></span>
      <span class='icon-bar'></span>
      <span class='icon-bar'></span>
      <span class='icon-bar'></span>

      </button>
      <a class='navbar-brand' href="/">Home</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-right navbar-nav">
        {% if current_user.is_authenticated %}
        <li style='color:white;padding:15px;'>{{current_user.username}}</li>
        <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
        <li><a href="{{url_for('auth.logout')}}">Sign Out</a></li>
        {% else %}
        <li><a href="{{url_for('auth.login')}}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>

app/templates/profile/profile.html
{% extends 'base.html'%}
{% block styles %}
  {{ super() }}
  <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
  <link rel="stylesheet" href="{{url_for('static',filename='./css/index.css') }}" type='text/css'>
{% endblock %}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{users.username| capitalize}} </h3>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if users.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>
</div>
</div>
  <h2 class='text-primary'>Your Blogs</h2>
  <div class="row">
    {% for blog in blogs %}
    <div class="col-sm-6">
      <ul class='list-unstyled '>
        <li class=style>
          <h3 class=text-primary>{{pitch.title}}</h3>
          <h4>{{blog.description}}</h4>
        </li> <hr> <br>
        </ul>
    </div>

    {% endfor %}
  </div>
{% endblock %}